package cuz.gpa;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn

@SpringBootApplication
@MapperScan("cuz.gpa.mapper")
public class GpaApplication {
	@GetMapping("/")
	public String hello(){return "Hello Spring Boot";}


	public static void main(String[] args) {
		SpringApplication.run(GpaApplication.class, args);
	}
}
